import streamlit as st
from PIL import Image
import numpy as np
import time
import os
import pandas as pd

st.set_page_config(page_title='Image classification',
                   page_icon='🐼',
                   layout='wide')

st.title('Welcome to image classification page!👋🏻')
st.markdown('---')

dir_name = 'image_exas'
placeholder_image = st.empty()

st.warning('The above example images are all generated by AI.')
st.markdown('---')
st.write("<p style='font-size:20px;'>数据集cifar100，它有 100 个类，每个类包含 600 个图像。\
         每个类别有 500 张训练图像和 100 张测试图像。 CIFAR-100 中的 100 个类分为 20 个超类。每个图像都带有一个类和一个超类标签。</p>", unsafe_allow_html=True)

st.markdown('''
| Superclass                    | Classes                                                    |
|------------------------------|------------------------------------------------------------|
| aquatic mammals              | beaver, dolphin, otter, seal, whale                       |
| fish                         | aquarium fish, flatfish, ray, shark, trout                 |
| flowers                      | orchids, poppies, roses, sunflowers, tulips               |
| food containers              | bottles, bowls, cans, cups, plates                        |
| fruit and vegetables         | apples, mushrooms, oranges, pears, sweet peppers           |
| household electrical devices | clock, computer keyboard, lamp, telephone, television     |
| household furniture          | bed, chair, couch, table, wardrobe                         |
| insects                      | bee, beetle, butterfly, caterpillar, cockroach             |
| large carnivores             | bear, leopard, lion, tiger, wolf                           |
| large man-made outdoor things| bridge, castle, house, road, skyscraper                   |
| large natural outdoor scenes | cloud, forest, mountain, plain, sea                        |
| large omnivores and herbivores| camel, cattle, chimpanzee, elephant, kangaroo            |
| medium-sized mammals         | fox, porcupine, possum, raccoon, skunk                     |
| non-insect invertebrates     | crab, lobster, snail, spider, worm                         |
| people                       | baby, boy, girl, man, woman                               |
| reptiles                     | crocodile, dinosaur, lizard, snake, turtle                 |
| small mammals                | hamster, mouse, rabbit, shrew, squirrel                   |
| trees                        | maple, oak, palm, pine, willow                             |
| vehicles 1                   | bicycle, bus, motorcycle, pickup truck, train              |
| vehicles 2                   | lawn-mower, rocket, streetcar, tank, tractor               |
''')

with placeholder_image:
    for filename in os.listdir(dir_name):
        filepath = os.path.join(dir_name, filename)
        st.image(filepath, width=420)
        time.sleep(1.5)

